dfinity/sol-rpc-canister

- canister/scripts/provision.sh
- canister/src/providers/mod.rs
1. Modify the `dRPC` provider to support API keys
2. Switch Ankr for Helius as default provider, since Ankr limits the total number of API keys that can be used to 3, meaning that currently we have a single API key for Solana (2 are for the EVM RPC canister for prod/staging)
3. Fix URL for Helius: the URL for mainnet and devnet was switched.
> fix: API keys

- canister/src/candid_rpc/mod.rs
- canister/src/main.rs
- canister/src/metrics/mod.rs
- canister/src/rpc_client/mod.rs
Follow-up on #52 to use the `method` specified by the JSON-RPC request for metrics purposes instead of having a separate enum.
> refactor: use method from JSON-RPC request for metric

- README.md
- SECURITY.md
- libs/client/README.md
- libs/client/src/request/mod.rs
- libs/types/README.md
Add README instructions to help projects getting started.
> docs: Add basic README instructions

- integration_tests/tests/solana_test_validator.rs
(XC-289) Use calls to the SOL RPC canister `getSlot` and `getBlock` endpoints to fetch the latest blockhash when sending a transaction with the `sendTransaction` endpoint in the `solana_test_validator` integration tests.
> test: use SOL RPC canister to fetch blockhash in integration test

- examples/basic_solana/basic_solana.did
- examples/basic_solana/src/lib.rs
- examples/basic_solana/src/main.rs
- examples/basic_solana/src/state.rs
- examples/basic_solana/tests/tests.rs
- libs/client/src/lib.rs
- libs/client/src/request/mod.rs
- libs/client/src/request/tests.rs
- libs/types/src/solana/request/mod.rs
Follow-up on #75 that improves the `SolRpcClient` by being able to set in the client builder a default commitment level that will be used by the built client for all future requests. This is similar to what the Solana client offers with [`new_with_commitment`](https://docs.rs/solana-client/latest/solana_client/rpc_client/struct.RpcClient.html#method.new_with_commitment).
> feat: default commitment level for `SolRpcClient`

- canister/scripts/examples.sh
Solana introduced a new transaction format with [versioned transactions](https://solana.com/de/developers/guides/advanced/versions). The calls for `getBlock` and `getTransaction` must specify a `maxSupportedTransactionVersion` (currently the most recent version is `0`) to avoid failing in case the response contains any version `0` transactions.
> fix: set `maxSupportedTransactionVersion` to zero for end-to-end tests

- canister/src/main.rs
- integration_tests/src/lib.rs
- integration_tests/tests/tests.rs
The endpoint `verifyApiKey` is useful for debugging and testing purposes to ensure that an API key for a given provider is correctly set. This is also obviously a sensitive endpoint and proper access control should be in place to avoid security issues such as leaking the API key. An integration test with Pocket IC was added to ensure that is the case.
> test: integration test for `verifyApiKey`

- canister/scripts/provision.sh
Solana JSON RPC providers use the same API key for Solana Mainnet or Devnet so that doing this distinction in the script to provision API keys is superfluous.
> ci: simplify API keys provisioning script

- canister/scripts/examples.sh
- canister/sol_rpc_canister.did
- canister/src/main.rs
- canister/src/rpc_client/json/mod.rs
- canister/src/rpc_client/mod.rs
- canister/src/rpc_client/sol_rpc/mod.rs
- canister/src/rpc_client/tests.rs
- examples/basic_solana/basic_solana.did
- examples/basic_solana/src/main.rs
- examples/basic_solana/tests/tests.rs
- integration_tests/tests/solana_test_validator.rs
- integration_tests/tests/tests.rs
- libs/client/src/lib.rs
- libs/client/src/request/mod.rs
- libs/client/src/request/tests.rs
- libs/types/src/lib.rs
- libs/types/src/response/mod.rs
- libs/types/src/solana/request/mod.rs
(XC-325) Add support for the `getTokenAccountBalance` Solana RPC method.
> feat: add support for `getTokenAccountBalance` RPC method

- integration_tests/tests/solana_test_validator.rs
(XC-291) Leverage `ClientBuilder::with_default_commitment` to avoid having to specify the commitment level in all request parameters in `solana_test_validator.rs`.
> test: use default commitment for client in `solana_test_validator.rs`

- libs/client/src/lib.rs
Hide the mock response setup in the documentation for the SOL RPC client `get_account_info` method.
> docs: hide setup in method documentation

- libs/types/src/lib.rs
- libs/types/src/tests.rs
(XC-291) Serialize the new `VecWithMaxLen` type to `Vec` (i.e. add `#[serde(into = "Vec<T>")]` annotation to type) and add some unit tests to ensure encoding/decoding round trips with Candid are successful when expected or fail when the underlying data is too long.
> refactor: Serialize `VecWithMaxLen` properly

- canister/scripts/provision.sh
- canister/sol_rpc_canister.did
- canister/src/providers/mod.rs
- integration_tests/tests/tests.rs
- libs/types/src/rpc_client/mod.rs
(XC-354) Add Chainstack as a supported RPC provider for both Mainnet ande Devnet. It is currently a non-default provider for both Solana clusters.
> chore: add Chainstack RPC provider

- README.md
Follow-up on #116 to list the supported providers.
> docs: supported providers

- canister/src/providers/mod.rs
- canister/src/providers/tests.rs
- libs/types/src/rpc_client/mod.rs
The notion of default/non-default providers was only useful when `Equality` was chosen as consensus strategy and no providers was explicitly specified, in which case the "default" providers would be selected. This PR removes the notion of default/non-default providers by replacing with an ordered list of providers for a given Solana cluster. The previous notion of "default" providers simpy correspond to the first three providers in that list.
> refactor: remove default/non-default providers

- canister/src/main.rs
- integration_tests/tests/tests.rs
Logs at level `TraceHttp` where not added to the canister response when queried via the HTTP endpoint `/logs` (was probably forgotten in #13).
> fix: missing `TraceHttp` logs

- .github/workflows/ci.yml
- Cargo.lock
- end_to_end_tests/Cargo.toml
- end_to_end_tests/src/lib.rs
- end_to_end_tests/tests/end_to_end.rs
- examples/basic_solana/src/lib.rs
(XC-339) Add an end-to-end test for `sendTransaction` using a durable nonce instead of a recent blockhash to construct the Solana transaction.
> test: durable nonce end-to-end test

- canister/src/rpc_client/tests.rs
- integration_tests/tests/tests.rs
- libs/client/Cargo.toml
- libs/client/src/lib.rs
- libs/client/src/request/mod.rs
- libs/client/src/request/tests.rs
- libs/types/src/lib.rs
- libs/types/src/solana/request/mod.rs
Add explicit types for all RPC request builders, and methods to set optional request parameters (e.g. `with_min_context_slot()`, `.with_commitment()`).
> chore: add helper methods for request builders

- canister/src/rpc_client/json/mod.rs
- libs/types/src/solana/request/mod.rs
Inline the public `is_default_config()` method for various request parameters that were only used when serializing said request parameters.
> refactor: inline request parameters `is_default_config` methods

- canister/scripts/examples.sh
In the example call to `getSignaturesForAddress` in `examples.sh`, the `limit` request parameter was incorrectly set to an `opt nat16` whereas it should have been an `opt nat32`. This led to a Candid error when running the end-to-end tests and thus the `getSignaturesForAddress` endpoint was not being correctly tested.
> fix: change `nat16` to `nat32` in examples

- examples/basic_solana/build.sh
- examples/basic_solana/local/dfx.json
- examples/basic_solana/mainnet/dfx.json
Use a build script to deploy `basic_solana` locally and on Mainnet which checks what platform it is running to ensure proper handling of `llvm`.
> chore: use build script for `basic_solana` deployment

- libs/client/src/ed25519.rs
(XC-403) Until now, calls to the `sign_with_schnorr` management canister endpoint were incorrectly using the same fee for local and test keys, whereas the local key requires the same fee as the production key, see [the documentation](https://internetcomputer.org/docs/references/t-sigs-how-it-works#local-development-environment).
> fix: use correct fee for t-sig with local development key

- Cargo.lock
- libs/client/Cargo.toml
Bump the `sol_rpc_client` crate to `v1.0.1`.
> chore: bump `sol_rpc_client` to `v1.0.1`

- README.md
- examples/basic_solana/README.md
- libs/client/README.md
- libs/client/src/lib.rs
- libs/types/README.md
- libs/types/src/lib.rs
(XC-405) Add detailed build requirements to the top-level READMEs as well as the READMEs and rustdocs for the sol_rpc_client` and `sol_rpc_types` crates. These requirements include mentions of:
* patching dependencies with `[path.crates.io]`
* setting appropriate flags for the `getrandom` dependency
* setting up LLVM with `brew` on macOS
Also add a note about the requirements in the `basic_solana` example and update the LLVM instructions there.
> docs: add build requirements to READMEs and rustdoc 

- README.md
(XC-405) Add section to the top-level README on how to deploy a local instance of the SOL RPC canister. Also refer to this section in the "Usage" section.
> docs: add deployment instructions

- Cargo.lock
- Cargo.toml
- end_to_end_tests/Cargo.toml
- end_to_end_tests/src/lib.rs
- integration_tests/Cargo.toml
- integration_tests/src/lib.rs
- integration_tests/src/wallet.rs
- libs/client/Cargo.toml
- libs/client/src/ed25519.rs
- libs/client/src/fixtures/mod.rs
- libs/client/src/lib.rs
- libs/client/src/request/mod.rs
Add a `try_send` method to the client in `sol_rpc_client` that doesn't panic if sending the request fails and instead returns the resulting error. The bulk of this change involves a refactoring to use `ic_error_types::RejectCode` instead of `ic_cdk::api::call::RejectionCode` wherever possible in the repository.
BREAKING CHANGE: Various public methods now return a `Result<(..., (ic_error_types::RejectCode, String))>` instead of a `Result<(..., (ic_cdk::api::call::RejectionCode, String))>` previously.
> feat!: add `try_send` method to SOL RPC client

- libs/types/src/rpc_client/mod.rs
Replace `RpcServices` (which was likely copy-pasted from the EVM RPC canister repository) by `RpcSources`.
> fix: typo in Rust documentation of `ConsensusStrategy`

- README.md
- examples/basic_solana/README.md
(XC-453) Add "Deployment to ICP Ninja" section including button with link in `basic_solana` README.
> docs: Add link to ICP Ninja in `basic_solana` README

- .github/workflows/publish.yml
- .github/workflows/release.yml
- canister/Cargo.toml
Currently, `release-plz` runs into issues when trying to determine the next version of the `sol_rpc_canister` crate. This is because the `sol_rpc_canister` crate is a binary crate and hence not published on [crates.io](crates.io). However, since a release tag exists for the crate, `release-plz` tries to download the latest release from [crates.io](crates.io) and fails. See [this failed release pipeline run](https://github.com/dfinity/sol-rpc-canister/actions/runs/17233112571) for example.
I've opened [a PR](https://github.com/release-plz/release-plz/pull/2357) to fix this issue in the upstream release-plz repository, and updated the release pipeline here to build the release-plz GitHub action from source to include those changes. This is a temporary solution until the changes are merged …
> fix: release pipeline

- examples/basic_solana/README.md
Expand the tip on deployment of the `basic_solana` example after downloading it from ICP Ninja by mentioning how to adapt the `solana_network` `init_arg` value to use a public RPC endpoint.
> docs: expand `basic_solana` tip on local usage from ICP Ninja

- .github/workflows/ci.yml
- examples/basic_solana/ninja/Cargo.toml
(XC-454) Since #222 was merged, re-enable the CI pipeline step to ensure the `Cargo.toml` for the ICP Ninja deployment of `basic_solana` is up-to-date, and group it with the other `icp-ninja-tests` added in #217.
> ci: re-enable `check-ninja-cargo-toml` in CI pipeline

- canister/src/rpc_client/mod.rs
Previously, the `response_size_estimate` parameter in the RPC config was ignored when calling `getBlock` on the SOL RPC canister. This PR ensures that the value is properly respected.
> fix: do not ignore `response_size_estimate` for `getBlock`

- .github/workflows/ci.yml
- canister/hidden_endpoints.txt
This PR adds a step to the CI pipeline that runs `ic-wasm check-endpoints` to verify that there are no accidentally or maliciously exported canister endpoints in the canister's WASM.
> ci: check canister endpoints with `ic-wasm`
